version: '2.1'
services:
    db:
        build: ../Database
        image: turnierserver:database
        volumes:
            - dbdata:/var/lib/postgresql/data
   
    datastore:
        build: ../Datastore
        image: turnierserver:datastore
        volumes:
            - ftpdata:/home/ftpusers
            - ftpusers:/etc/pure-ftpd/passwd

    api:
        build: ../API
        image: turnierserver:api
        links:
            - db
            - datastore
        depends_on:
            db:
                condition: service_healthy
            datastore:
                condition: service_started
        ports:
            - "8000:80"

    backend:
        build: ../Backend/docker
        image: turnierserver:backend
        links:
            - datastore
        depends_on:
            - datastore

volumes:
    dbdata:
        external: true
    ftpdata:
        external: true
    ftpusers:
        external: true
